In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("data/missions.csv", encoding="utf-8-sig") 
df.head()

,order_item_id,type,order_id,item_id,requested_quantity,processed_quantity,start_location_id,goal_location_id,start_y,start_x,goal_y,goal_x,rack_id,status,priority,assigned_agent
0,1001,PICK,NaN,KH004,1,0,0,130,2,9,5,6,G010,WAIT,1,1
1,1002,MOVE,8001.0,NX002,10,0,120,301,1,4,8,14,A012,WAIT,2,4
2,1003,MOVE,5001.0,KH003,9,0,200,101,9,12,1,12,H005,WAIT,2,5
3,1004,INBOUND,7001.0,KH004,23,0,0,130,3,5,10,9,G003,WAIT,2,3
4,1005,OUTBOUND,6001.0,HK003,19,0,400,201,5,13,1,3,C002,WAIT,1,4

In [6]:
n = 240 # 행 개수

# rack_id 리스트 생성 (A001~U012)
rack_letters = [chr(ord('A') + i) for i in range(21)]  # 'A' ~ 'U'
rack_numbers = [f"{j:03d}" for j in range(1, 13)]      # 001 ~ 012
rack_id_list = [f"{row}{col}" for row in rack_letters for col in rack_numbers]

num_agents = 8  # 최대 에이전트 수
assigned_agents = np.tile(np.arange(1, num_agents+1), int(np.ceil(n/num_agents)))[:n]
np.random.shuffle(assigned_agents)  # 랜덤 분배


item_id_prefixes = ['HK', 'KH', 'NX']
item_id_list = [f"{prefix}{str(num).zfill(3)}" for prefix in item_id_prefixes for num in range(1, 6)]

columns = [
    "order_item_id", "type", "order_id", "item_id", "requested_quantity", "processed_quantity",
    "start_location_id", "goal_location_id", "start_y", "start_x", "goal_y", "goal_x",
    "rack_id", "status", "priority", "assigned_agent"
]

df = pd.DataFrame({
    "order_item_id": np.arange(1001, 1001 + n),
    "type": np.random.choice(["INBOUND", "OUTBOUND"], n),
    "order_id": np.random.choice([5001, 6001, 7001, 8001, None], n),
    "item_id": np.random.choice(item_id_list, n),  # 여기서 지정한 리스트에서 랜덤 선택
    "requested_quantity": np.random.randint(1, 25, n),
    "processed_quantity": np.zeros(n, dtype=int),
    "start_location_id": np.random.choice([0, 100, 120, 200, 201, 400, 500], n),
    "goal_location_id": np.random.choice([101, 130, 201, 301, 400, 600], n),
    "start_y": np.random.randint(1, 11, n),
    "start_x": np.random.randint(1, 15, n),
    "goal_y": np.random.randint(1, 11, n),
    "goal_x": np.random.randint(1, 15, n),
    "rack_id": np.random.choice(rack_id_list, n), 
    "status": "WAIT",
    "priority": np.random.choice([1,2,3], n),
    "assigned_agent": assigned_agents 
})

df = df[columns]

df.head(35)

,order_item_id,type,order_id,item_id,requested_quantity,processed_quantity,start_location_id,goal_location_id,start_y,start_x,goal_y,goal_x,rack_id,status,priority,assigned_agent
0,1001,INBOUND,7001,HK003,23,0,400,400,5,10,5,7,S002,WAIT,3,3
1,1002,INBOUND,8001,NX004,17,0,0,201,4,8,2,5,Q012,WAIT,3,1
2,1003,INBOUND,None,NX002,16,0,120,301,2,13,2,8,S003,WAIT,2,2
3,1004,OUTBOUND,5001,KH002,18,0,400,400,5,1,7,2,O012,WAIT,2,2
4,1005,INBOUND,6001,HK001,10,0,0,301,9,3,5,6,A009,WAIT,2,7
5,1006,OUTBOUND,5001,KH005,19,0,400,400,4,5,8,5,H009,WAIT,1,6
6,1007,OUTBOUND,7001,HK004,14,0,201,130,2,7,4,5,G002,WAIT,3,3
7,1008,OUTBOUND,8001,KH005,2,0,400,130,8,7,5,10,K005,WAIT,3,1
8,1009,INBOUND,7001,KH005,15,0,0,600,2,1,6,7,H012,WAIT,1,1
9,1010,INBOUND,None,NX003,15,0,0,301,2,9,5,13,D009,WAIT,3,2
10,1011,INBOUND,None,HK005,19,0,100,130,8,5,10,11,A011,WAIT,2,5
11,1012,INBOUND,8001,NX001,1,0,100,400,2,10,9,6,K011,WAIT,3,1
12,1013,OUTBOUND,6001,KH003,23,0,400,400,6,1,4,10,J002,WAIT,1,5
13,1014,OUTBOUND,None,NX004,24,0,500,101,7,12,3,3,Q006,WAIT,3,8
14,1015,INBOUND,None,HK001,23,0,200,201,7,5,7,2,C001,WAIT,1,8
15,1016,OUTBOUND,7001,HK002,14,0,400,400,10,3,7,7,O006,WAIT,2,1
16,1017,OUTBOUND,6001,HK005,6,0,120,301,4,2,6,9,H006,WAIT,1,4
17,1018,OUTBOUND,6001,HK005,3,0,200,301,10,7,10,14,R007,WAIT,1,5
18,1019,OUTBOUND,5001,NX004,15,0,0,600,3,3,7,3,Q002,WAIT,2,7
19,1020,INBOUND,8001,NX004,16,0,400,201,10,12,10,4,F003,WAIT,2,7
20,1021,INBOUND,6001,HK002,8,0,100,301,10,9,5,11,I005,WAIT,2,5
21,1022,INBOUND,5001,NX003,21,0,400,130,3,8,7,9,J012,WAIT,3,8
22,1023,INBOUND,8001,NX003,15,0,200,101,3,13,9,3,P003,WAIT,3,2
23,1024,INBOUND,5001,NX005,14,0,200,301,2,9,5,7,S003,WAIT,3,8
24,1025,OUTBOUND,8001,NX003,14,0,100,301,2,12,6,2,L002,WAIT,3,8
25,1026,INBOUND,None,NX002,22,0,0,600,6,11,5,4,N003,WAIT,1,4
26,1027,OUTBOUND,None,HK004,8,0,201,101,3,3,5,1,E009,WAIT,2,7
27,1028,INBOUND,7001,KH005,12,0,200,130,3,4,4,13,B011,WAIT,2,8
28,1029,OUTBOUND,5001,NX001,20,0,0,201,3,12,1,13,R001,WAIT,3,8
29,1030,INBOUND,5001,HK004,6,0,120,600,7,2,5,5,K011,WAIT,1,1
30,1031,OUTBOUND,5001,HK003,6,0,201,130,4,3,10,7,P007,WAIT,2,2
31,1032,OUTBOUND,None,KH005,6,0,100,301,5,7,4,11,Q009,WAIT,3,1
32,1033,INBOUND,None,HK004,7,0,400,600,5,12,2,11,D010,WAIT,3,4
33,1034,INBOUND,7001,NX002,18,0,201,301,3,5,5,14,F003,WAIT,1,3
34,1035,OUTBOUND,8001,HK004,15,0,100,101,5,3,7,14,L008,WAIT,2,4

In [13]:
df.to_csv("missions.csv", index=False, encoding="utf-8-sig")